# src/owlroost/workspace/default_toml.py
#
# Copyright (c) 2026 John Leonard
# SPDX-License-Identifier: GPL-3.0-or-later
# See LICENSE file in repository root.

"""
Default workspace.toml rendering.

Notes
-----
Renders the default ``workspace.toml`` file
created by ``roost workspace init``.

This module owns presentation only.

It does not:

    * write files
    * inspect workspaces
    * mutate the filesystem

Those responsibilities belong to
workspace.operations.

Architectural Invariants
------------------------

The renderer composes independent
configuration sections.

Each section owns one conceptual
portion of the generated TOML.

This organization intentionally makes
future reordering, insertion, and
removal of sections straightforward.
"""

from __future__ import annotations

from pathlib import Path

from owlroost.workspace.levers.context import (
    default_household_library_strings,
)

# =========================================================
# Section Rendering
# =========================================================


def _render_workspace_metadata(
    workspace_dir: Path,
) -> list[str]:
    """
    Render workspace identity and
    descriptive metadata.
    """

    name = workspace_dir.name

    return [
        "# =====================================================",
        "# ROOST Workspace",
        "#",
        "# This file was generated by ROOST.",
        "#",
        "# Adjust values as desired.",
        "# =====================================================",
        "",
        f'title = "{name} - human readable"',
        "",
        'description = """\\',
        "This is an autogenerated description.",
        "",
        "Edit this file to customize the workspace.",
        '"""',
    ]


def _render_context_paths() -> list[str]:
    """
    Render context path overrides.

    Edit these values to customize the
    effective planning context for this
    workspace.
    """

    return [
        "# -----------------------------------------------------",
        "# Context Paths",
        "# -----------------------------------------------------",
        "#",
        "# These values override the default",
        "# planning context path observations.",
        "#",
        "[context.paths]",
        "",
        'cases = "./cases"',
        'results = "./results"',
    ]


def _render_household_libraries() -> list[str]:
    """
    Render household library search
    policy.

    Edit, reorder, remove, or extend
    this list to customize the search
    policy for this workspace.
    """

    lines = [
        "# -----------------------------------------------------",
        "# Household Libraries",
        "# -----------------------------------------------------",
        "#",
        "# Override the default household",
        "# library search path for this",
        "# workspace.",
        "#",
        "# Household libraries are searched",
        "# in the order listed below.",
        "#",
        "# Paths may be relative to this",
        "# workspace, use '~' for the user",
        "# home directory, or '<builtin>'",
        "# for the ROOST built-in library.",
        "",
        "households = [",
    ]

    for value in default_household_library_strings():
        lines.append(f'    "{value}",')

    lines.append("]")

    return lines


# =========================================================
# Public API
# =========================================================


def render_workspace_toml(
    workspace_dir,
) -> str:
    """
    Render the default workspace.toml.

    Parameters
    ----------
    workspace_dir
        Workspace directory.

    Returns
    -------
    str
        Complete TOML document.
    """

    workspace_dir = Path(
        workspace_dir,
    ).resolve()

    sections = (
        lambda: _render_workspace_metadata(
            workspace_dir,
        ),
        _render_context_paths,
        _render_household_libraries,
    )

    lines: list[str] = []

    for i, section in enumerate(
        sections,
    ):
        if i:
            lines.append("")

        lines.extend(section())

    lines.append("")

    return "\n".join(
        lines,
    )
