-include $(shell roost settings makefile)  # load roost default makefile targets
-include ./makefile.mk                     # load folder-local defaults

# Add additional makefile targets
# to makefile.mk file.  It will be included
# as necessary.
